services:
  normaliser:
    image: ${IMAGE}
    env_file: .env
    deploy:
      replicas: 1
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/healthz || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 10
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --workers ${UVICORN_WORKERS}
    restart: unless-stopped
